/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openkm.okmsynchronize.view;

import com.openkm.okmsynchronize.model.SynchronizeError;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author abujosa
 */
public class SynchronizeLogView extends java.awt.Dialog {

    /**
     * Creates new form SynchronizeViewLog
     */
    public SynchronizeLogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Creates new form SynchronizeViewLog
     */
    public SynchronizeLogView(java.awt.Frame parent, String logPath, boolean modal) {
        super(parent, modal);
        initComponents();
        this.logPath = logPath;
        try {        
            readLogfile(logPath);
        } catch (SynchronizeError ex) {
            
        }
    }
    
    public void refreshViewLog(String logPath) throws SynchronizeError {
        this.logPath = logPath;
        textLog.setText("");
        readLogfile(logPath);
    }
    
    public void addButtonCloseActionListener(ActionListener l) {buttonClose.addActionListener(l); }
    public void addButtonRefreshActionListener(ActionListener l) {buttonRefresh.addActionListener(l); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonRefresh = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JEditorPane();

        setMinimumSize(new java.awt.Dimension(1000, 700));
        setTitle("View log");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonRefresh.setText("Refresh");
        buttonRefresh.setToolTipText("Refresh log view");
        buttonRefresh.setDisplayedMnemonicIndex(0);
        jPanel1.add(buttonRefresh);

        buttonClose.setText("Close");
        buttonClose.setToolTipText("Close view log dialog");
        buttonClose.setDisplayedMnemonicIndex(0);
        jPanel1.add(buttonClose);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(textLog);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * Read log file
     */
    private void readLogfile(String path) throws SynchronizeError {
        File log = new File(path);
        InputStreamReader in = null;
        try {
            in = new FileReader(log);
            textLog.read(in, in);
        } catch (FileNotFoundException ex) {
            throw new SynchronizeError("", "" , ex);
        } catch (IOException ex) {
            throw new SynchronizeError("", "" , ex);
        }       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SynchronizeLogView dialog = new SynchronizeLogView(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private String logPath;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane textLog;
    // End of variables declaration//GEN-END:variables
}
